# Generated by Django 5.0.6 on 2024-07-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0004_remove_lobbydata_numberofplayers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobbydata',
            name='isActiveLobby',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
