# Generated by Django 5.0.6 on 2024-06-14 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPairingData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tournament_id', models.CharField(max_length=60)),
                ('winner', models.CharField(blank=True, max_length=60, null=True)),
                ('round_id', models.CharField(blank=True, max_length=60, null=True)),
                ('linkToJoin', models.CharField(blank=True, max_length=60, null=True)),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_id', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
