# Generated by Django 5.0.6 on 2024-06-21 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentPairings', '0002_alter_tournamentpairingdata_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentpairingdata',
            name='linkToJoin',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
