# Generated by Django 5.0.2 on 2024-02-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'verbose_name': 'Login', 'verbose_name_plural': 'Logins'},
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=255),
        ),
    ]
