# Generated by Django 5.0.2 on 2024-02-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_login_options_login_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={},
        ),
        migrations.RemoveField(
            model_name='login',
            name='password',
        ),
    ]
