# Generated by Django 5.0.2 on 2024-03-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='nick_name',
            field=models.CharField(default='Richard Bell', max_length=60),
        ),
    ]
