# Generated by Django 5.0.4 on 2024-04-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useraccount_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='nick_name',
            field=models.CharField(default='Abigail Moore', max_length=60),
        ),
    ]
