# Generated by Django 5.0.2 on 2024-02-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_useraccount_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='picture',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(editable=False, max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
