# Generated by Django 5.0.2 on 2024-03-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_useraccount_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='nick_name',
            field=models.CharField(default='Jeffrey Hodges', max_length=60),
        ),
    ]
