# Generated by Django 5.0.2 on 2024-03-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_useraccount_nick_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='name',
            new_name='login',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='nick_name',
            field=models.CharField(default='Kari Clark', max_length=60),
        ),
    ]
