# Generated by Django 5.0.2 on 2024-03-21 08:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_name_useraccount_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='nick_name',
            field=models.CharField(default='Christina Brown', max_length=60),
        ),
    ]
