# Generated by Django 5.0.3 on 2024-03-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_name_useraccount_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='nick_name',
            field=models.CharField(default='Christian Smith', max_length=60),
        ),
    ]
