# Generated by Django 5.0.3 on 2024-03-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_useraccount_friends_alter_useraccount_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='nick_name',
            field=models.CharField(default='Lynn Morrison', max_length=60),
        ),
    ]
