# Generated by Django 5.0.3 on 2024-04-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_useraccount_nick_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='nick_name',
            field=models.CharField(default='Amanda Reed', max_length=60),
        ),
    ]
