services:
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # volumes:
    #   - app:/app

# volumes:
#   app:
#     driver: local
#     driver_opts:
#       type: none
#       device: ./frontend
#       o: bind
