services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - backend
    ports:
      - 3000:3000
    volumes: 
      - ./frontend/:/app
      - /app/node_modules
      - /app/.next
  
  ws-server:
    container_name: ws-server
    build:
      context: ./frontend/ws-server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 6500:6500
    volumes:
      - ./frontend/ws-server/:/server
      - /server/node_modules

  db:
    container_name: database
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - /Users/julzibot/goinfre/ft_transcendence/.dbdata:/var/lib/postgresql/data
      # - /Users/miky/42mac/ft_transcendence/.dbdata:/var/lib/postgresql/data
      # - /home/mstojilj/goinfre/.dbdata:/var/lib/postgresql/data
      # - /home/anloisea/goinfre/ft_transcendence/.dbdata:/var/lib/postgresql/data
    ports:
      - 33066:5432


  backend:
    container_name: backend
    build:
      context: ./backend/core
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - db
      # - redis
    volumes:
      - ./backend/core/:/app
    env_file:
      - ./backend/core/.env.example

  # redis:
  #   container_name: redis
  #   image: redis:7
  #   restart: always
  #   ports: 
  #     - 33067:6379
  #   volumes:
  #     - /Users/julzibot/goinfre/ft_transcendence/.redis:/data
  #     # - /home/anloisea/goinfre/ft_transcendence/.redis:/data