# Generated by Django 5.0.6 on 2024-07-10 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCustomizationData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('background', models.SmallIntegerField(default=0)),
                ('palette', models.SmallIntegerField(default=0)),
                ('bgColor', models.CharField(default='#ff0000')),
                ('opacity', models.SmallIntegerField(default=0)),
                ('sparks', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Customization Data',
                'verbose_name_plural': 'Game Customization Data',
            },
        ),
    ]
