# Generated by Django 5.0.6 on 2024-07-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameCustomization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecustomizationdata',
            name='opacity',
            field=models.SmallIntegerField(default=80),
        ),
    ]
