# Generated by Django 5.1.1 on 2024-10-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mode', models.PositiveSmallIntegerField(choices=[(0, 'Local'), (1, 'AI'), (2, 'Online'), (3, 'Tournament')], default=0)),
                ('score1', models.PositiveIntegerField(default=0)),
                ('score2', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Game Match',
                'verbose_name_plural': 'Game Matches',
            },
        ),
    ]
