# Generated by Django 5.1.1 on 2024-11-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamematch',
            name='tournament',
        ),
        migrations.AddField(
            model_name='gamematch',
            name='tournamentLink',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
