# Generated by Django 5.0.8 on 2024-08-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
