# Generated by Django 5.0.3 on 2024-04-08 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboarddata',
            options={'verbose_name': 'Dashboard Data', 'verbose_name_plural': 'Dashboard Data'},
        ),
        migrations.AlterField(
            model_name='dashboarddata',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
