# Generated by Django 5.0.3 on 2024-04-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_dashboarddata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboarddata',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='dashboarddata',
            name='ratio',
        ),
    ]
