# Generated by Django 5.0.6 on 2024-07-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_dashboarddata_games_played_dashboarddata_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='prevResult',
            field=models.BooleanField(default=False),
        ),
    ]
