# Generated by Django 5.0.6 on 2024-07-05 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPairingData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tournament_id', models.CharField(max_length=60)),
                ('round_id', models.CharField(blank=True, max_length=60, null=True)),
                ('linkToJoin', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
