# Generated by Django 5.0.6 on 2024-07-05 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournamentPairings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentpairingdata',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentpairingdata',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournamentpairingdata',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
