# Generated by Django 5.0.6 on 2024-06-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentdata',
            name='tournamentWinner',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
