# Generated by Django 5.0.6 on 2024-06-11 11:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_tournamentdata_tournamentwinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentdata',
            name='difficultyLevel',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tournamentdata',
            name='isActiveTournament',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tournamentdata',
            name='isPrivate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='tournamentdata',
            name='pointsPerGame',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tournamentdata',
            name='powerUps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='SOME', max_length=60, null=True), default=[], size=None),
        ),
        migrations.AddField(
            model_name='tournamentdata',
            name='timer',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentdata',
            name='numberOfPlayers',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
