# Generated by Django 5.0.6 on 2024-06-11 12:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournamentdata_difficultylevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentdata',
            name='powerUps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='SOME', max_length=60, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
