# Generated by Django 5.0.6 on 2024-07-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_tournamentdata_gamename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentdata',
            name='powerUps',
        ),
        migrations.AddField(
            model_name='tournamentdata',
            name='powerUps',
            field=models.BooleanField(blank=True, default=False, null=True),
            preserve_default=False,
        ),
    ]
