# Generated by Django 5.0.6 on 2024-06-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentParticipants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentparticipants',
            old_name='tournamentId',
            new_name='tournament_id',
        ),
    ]
