# Generated by Django 5.0.6 on 2024-06-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentParticipants', '0002_rename_tournamentid_tournamentparticipants_tournament_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentparticipants',
            old_name='user',
            new_name='userAccount',
        ),
    ]
