# Generated by Django 5.0.6 on 2024-06-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournamentParticipants', '0003_rename_user_tournamentparticipants_useraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentparticipants',
            old_name='userAccount',
            new_name='user',
        ),
    ]
