# Generated by Django 5.0.6 on 2024-07-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameCustomization', '0003_alter_gamecustomizationdata_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecustomizationdata',
            old_name='user_id',
            new_name='user',
        ),
    ]
