# Generated by Django 5.0.6 on 2024-07-02 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameCustomization', '0004_rename_user_id_gamecustomizationdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecustomizationdata',
            name='user',
        ),
    ]
