# Generated by Django 5.0.6 on 2024-07-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameCustomization', '0006_gamecustomizationdata_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecustomizationdata',
            old_name='user',
            new_name='user_id',
        ),
    ]
