# Generated by Django 5.0.6 on 2024-07-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameCustomization', '0007_rename_user_gamecustomizationdata_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecustomizationdata',
            options={'verbose_name': 'Game Customization Data', 'verbose_name_plural': 'Game Customization Data'},
        ),
    ]
