# Generated by Django 5.0.6 on 2024-07-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameCustomization', '0008_alter_gamecustomizationdata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecustomizationdata',
            name='opacity',
            field=models.SmallIntegerField(default=80),
        ),
    ]
