# Generated by Django 5.0.2 on 2024-03-27 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='to_user',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='requestor',
            field=models.CharField(choices=[('UID1', 'Uid1'), ('UID2', 'Uid2')], default='UID1', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='user_id1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_id1_friendrequests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='user_id2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_id2_friendrequests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id1_friendlists', to=settings.AUTH_USER_MODEL)),
                ('user_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id2_friendlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
