# Generated by Django 5.0.2 on 2024-03-27 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_remove_friendrequest_user_id1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendship',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
