# Generated by Django 5.0.6 on 2024-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dashboard Data',
                'verbose_name_plural': 'Dashboard Data',
            },
        ),
    ]
