# Generated by Django 5.0.6 on 2024-07-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarddata',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='tournaments_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dashboarddata',
            name='tournaments_won',
            field=models.IntegerField(default=0),
        ),
    ]
