# Generated by Django 5.0.7 on 2024-08-02 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_dashboarddata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboarddata',
            name='games_played',
        ),
    ]
