# Generated by Django 5.0.7 on 2024-08-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_dashboarddata_games_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboarddata',
            name='wins',
        ),
    ]
