# Generated by Django 5.0.6 on 2024-07-10 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('numberOfPlayers', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('isPrivate', models.BooleanField(blank=True, default=False, null=True)),
                ('difficultyLevel', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('isActiveTournament', models.BooleanField(blank=True, default=False, null=True)),
                ('pointsPerGame', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('timer', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('powerUps', models.BooleanField(blank=True, default=False, null=True)),
                ('round', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('gameName', models.CharField(blank=True, default='', null=True)),
                ('tournamentWinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_tournament', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
