# Generated by Django 5.0.6 on 2024-07-17 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentdata',
            name='gameName',
        ),
    ]
