# Generated by Django 5.1.1 on 2024-10-03 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_remove_tournamentdata_gamename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentdata',
            old_name='powerUps',
            new_name='power_ups',
        ),
    ]
