# Generated by Django 5.1.1 on 2024-11-03 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_tournamentmodel_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodel',
            name='maxPlayerNumber',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
