# Generated by Django 5.0.6 on 2024-07-02 11:55

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbyData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('numberOfPlayers', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('isPrivate', models.BooleanField(blank=True, default=False, null=True)),
                ('difficultyLevel', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('isActiveLobby', models.BooleanField(blank=True, default=False, null=True)),
                ('pointsPerGame', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('timer', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('powerUps', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='SOME', max_length=60, null=True), blank=True, default=list, null=True, size=None)),
                ('round', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('gameName', models.CharField(blank=True, default='', null=True)),
                ('lobbyWinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_lobby', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
