# Generated by Django 5.1.1 on 2024-10-29 11:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbyData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('difficultyLevel', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
                ('pointsPerGame', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(21)])),
                ('power_ups', models.BooleanField(default=False)),
                ('linkToJoin', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_creator', to=settings.AUTH_USER_MODEL)),
                ('lobbyWinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_lobby', to=settings.AUTH_USER_MODEL)),
                ('player1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_player2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lobby',
                'verbose_name_plural': 'Lobbies',
            },
        ),
    ]
