# Generated by Django 5.1 on 2024-08-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbydata',
            name='difficultyLevel',
        ),
        migrations.RemoveField(
            model_name='lobbydata',
            name='isPrivate',
        ),
        migrations.RemoveField(
            model_name='lobbydata',
            name='pointsPerGame',
        ),
        migrations.RemoveField(
            model_name='lobbydata',
            name='powerUps',
        ),
        migrations.RemoveField(
            model_name='lobbydata',
            name='timer',
        ),
    ]
