# Generated by Django 5.0.6 on 2024-07-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbydata',
            name='powerUps',
        ),
        migrations.AddField(
            model_name='lobbydata',
            name='powerUps',
            field=models.BooleanField(blank=True, default=False, null=True),
                  preserve_default=False,
        ),
    ]
