# Generated by Django 5.1.1 on 2024-10-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbydata',
            name='gameMode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('TOURNAMENT', 'Tournament')], default='ONLINE', max_length=10),
        ),
        migrations.AddField(
            model_name='lobbydata',
            name='tournamentLink',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lobbydata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
