# Generated by Django 5.1.1 on 2024-10-24 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lobby', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbydata',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lobbydata',
            name='lobbyWinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_lobby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lobbydata',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lobbydata',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_player2', to=settings.AUTH_USER_MODEL),
        ),
    ]
