# Generated by Django 5.0.6 on 2024-07-04 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_alter_lobbydata_powerups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbydata',
            name='numberOfPlayers',
        ),
        migrations.AddField(
            model_name='lobbydata',
            name='linkToJoin',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='lobbydata',
            name='player1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_player1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lobbydata',
            name='player2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lobby_player2', to=settings.AUTH_USER_MODEL),
        ),
    ]
