# Generated by Django 5.0.7 on 2024-07-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0005_alter_lobbydata_isactivelobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbydata',
            name='gameName',
        ),
    ]
