# Generated by Django 5.0.4 on 2024-04-16 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player1',
        ),
    ]
