# Generated by Django 5.0.4 on 2024-04-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_player1'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_id',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
